<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="F6646_vk07.aspx.cs" Inherits="F6646_vk07" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">



    <asp:GridView
        ID="gvAutot"
        runat="server"
        AllowSorting="True"
        AllowPaging="True"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True"
        OnSorting="gvAutot_Sorting"
        OnPageIndexChanging="gvAutot_PageIndexChanging"
        OnRowCancelingEdit="gvAutot_RowCancelingEdit"
        OnRowDeleting="gvAutot_RowDeleting"
        OnRowEditing="gvAutot_RowEditing"
        OnRowUpdating="gvAutot_RowUpdating" >
    </asp:GridView>

    <asp:Button ID="btnAddNew" runat="server" OnClick="btnAddNew_Click" Text="Lisää uusi auto" />



</asp:Content>

